M48
; DRILL file {KiCad (6.0.7)} date Sat Sep 24 19:09:10 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-24T19:09:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.6654Y-2.815
X4.6654Y-3.6417
X5.4921Y-2.815
X5.4921Y-3.6417
T0
M30
