M48
; DRILL file {KiCad (7.0.0)} date Sun Feb 19 16:47:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-19T16:47:10-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X6.2992Y-2.9921
X6.3Y-3.8189
X7.126Y-2.9921
X7.126Y-3.8189
T0
M30
