M48
; DRILL file {KiCad 7.0.5} date Fri Jul  7 17:48:48 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-07T17:48:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X6.2992Y-2.9921
X6.3Y-3.8189
X7.126Y-2.9921
X7.126Y-3.8189
T0
M30
