M48
; DRILL file {KiCad (6.0.5)} date Sat Jun 11 16:37:08 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-11T16:37:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.56Y-3.32
X6.69Y-3.39
X6.72Y-3.36
X6.79Y-3.23
X6.79Y-3.27
X6.8553Y-3.1353
X6.8853Y-3.1853
T2
X6.5Y-3.51
X6.6Y-3.51
X6.7Y-3.51
X6.8Y-3.51
X6.9Y-3.51
X7.0Y-3.51
T0
M30
