M48
; DRILL file {KiCad (6.0.1)} date Thu Apr 14 01:05:33 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-14T01:05:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X5.7Y-2.3
X5.7Y-2.4
X5.7Y-2.5
X5.7Y-2.6
X5.7Y-2.7
X6.1Y-2.3
X6.1Y-2.4
X6.1Y-2.5
X6.1Y-2.6
X6.1Y-2.7
T0
M30
